@echo off
set LOCAL_QWEN_INSTRUCT_MODEL=%~dp0..\models\Qwen3-1.7B-Instruct
set LOCAL_QWEN_MODEL=%~dp0..\models\Qwen3-1.7B
if exist "%LOCAL_QWEN_INSTRUCT_MODEL%" (
    set ATHENAI_QWEN_MODEL=%LOCAL_QWEN_INSTRUCT_MODEL%
) else if exist "%LOCAL_QWEN_MODEL%" (
    set ATHENAI_QWEN_MODEL=%LOCAL_QWEN_MODEL%
) else (
    set ATHENAI_QWEN_MODEL=Qwen/Qwen3-1.7B
)
set ATHENAI_QWEN_DEVICE=cuda:0
set ATHENAI_MOCK_LLM=0
set ATHENAI_REQUIRE_CUDA=1
set ATHENAI_MAX_NEW_TOKENS=1024
set ATHENAI_LONG_TASK_MAX_NEW_TOKENS=2048
set ATHENAI_TEMPERATURE=0.55
set ATHENAI_TOP_P=0.9
set ATHENAI_TOP_K=40
py -m uvicorn main:app --host 0.0.0.0 --port 8001
